link preview feature (QMUN-2042)
QuickBlox/ChatMessagesAdapter-android pull request #10
Opened 2017-07-17 13:10 UTC by tatanka987

- added request for getting data about link from open graph service;
- added view for displaying link preview info;
- added listener for listening click on view with link info;

Main functionality tested on inner sample.

2017-07-17 15:15 UTC, vfite requested changes
make changes

2017-07-17 15:15 UTC, vfite commented on chat-message-adapter/src/main/java/com/quickblox/ui/kit/chatmessage/adapter/QBMessagesAdapter.java
> +        holder.linkPreviewLayout.setVisibility(View.GONE);
а зачем тут скрывать ?  ты же скрываешь если urlsList.size() = 0.

2017-07-17 15:15 UTC, vfite commented on chat-message-adapter/src/main/java/com/quickblox/ui/kit/chatmessage/adapter/QBMessagesAdapter.java
> +            linkTitle = (TextView) linkPreviewLayout.findViewById(R.id.link_preview_title);
это что-то вообще странное, мы так ни в одном лейате не делаем. все try/cath и весь длинній метод нужно переделівать

2017-07-17 15:15 UTC, vfite commented on chat-message-adapter/src/main/java/com/quickblox/ui/kit/chatmessage/adapter/utils/LinkUtils.java
> +        if (link.startsWith("http") && !link.contains("://")){
непонятные махинации. URL или URLEncoder может распарсить протокол и хост отдельно. в сдк где-то подобный разбор есть

2017-07-17 15:15 UTC, vfite commented on chat-message-adapter/build.gradle
> +//        repository(url: rootProject.mainRepository) {
?

2017-07-17 15:48 UTC, tatanka987 commented on chat-message-adapter/src/main/java/com/quickblox/ui/kit/chatmessage/adapter/utils/LinkUtils.java
> +        if (link.startsWith("http") && !link.contains("://")){
open graph не всегда отдает нармальную ссылку на имедж, пришлось вручную править ссылки

2017-07-17 15:49 UTC, tatanka987 commented on chat-message-adapter/build.gradle
> +//        repository(url: rootProject.mainRepository) {
это временное решение чтоб собирался локальный репозиторий чтоб тестить на кумуникейте

2017-07-20 14:10 UTC, vfite requested changes
make changes

2017-07-20 14:10 UTC, vfite commented on chat-message-adapter/src/main/java/com/quickblox/ui/kit/chatmessage/adapter/QBMessagesAdapter.java
> +        final List<String> urlsList = LinkUtils.extractUrls(chatMessage.getBody());
я один вижу копипаст с кодом выше?

2017-07-20 14:10 UTC, vfite commented on chat-message-adapter/src/main/java/com/quickblox/ui/kit/chatmessage/adapter/QBMessagesAdapter.java
> +        if (urlsList.size() > 0) {
isEmpty специально для коллекций есть метод

2017-07-20 14:10 UTC, vfite commented on chat-message-adapter/src/main/java/com/quickblox/ui/kit/chatmessage/adapter/QBMessagesAdapter.java
> +            if (holder.messageTextView.getText().length() == urlsList.get(0).length()) {
тут непонятно что за проверка

2017-07-20 14:10 UTC, vfite commented on chat-message-adapter/src/main/java/com/quickblox/ui/kit/chatmessage/adapter/QBMessagesAdapter.java
> +                        imageView.setVisibility(View.GONE);
ты же понимаешь что лейаут у тебя будет прыгать, если ты до этого уже показал imageView

2017-07-20 14:10 UTC, vfite commented on chat-message-adapter/src/main/java/com/quickblox/ui/kit/chatmessage/adapter/QBMessagesAdapter.java
> +        if (linkTitle != null) {
нужны ли нам эти проверки? 
в общем лейауте у нас нет таких проверок на вьювы

2017-07-20 14:10 UTC, vfite commented on chat-message-adapter/src/main/java/com/quickblox/ui/kit/chatmessage/adapter/utils/QBLinkPreviewCashService.java
> +    public Observable<QBLinkPreview> getLinkPreview(final String url, final String token, boolean forceLoad) {
по сути бесмысленно здесь использовать Observable.
Во первых это добавляет в проект зависимость. Во вторых этот класс никто больше не использует и он не является классом высшего уровня.

2017-07-20 14:10 UTC, vfite commented on chat-message-adapter/src/main/java/com/quickblox/ui/kit/chatmessage/adapter/utils/LinkUtils.java
> +            link = link.replace(":/", "://");
дело в том что у тебя врнутри   link-и может быть ":/". Поэтому вручную никто линки не парсит. для этого есть матчеры и др тулзы.

2017-08-21 10:14 UTC, merged